apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: jellyfin-pv
  resources:
    requests:
      storage: 10Gi
