apiVersion: v1
kind: PersistentVolume 
metadata:
  name: jellyfin-pv
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual 
  nfs:
    path: /export/Data 
    server: 192.168.1.44
    readOnly: false 

