apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: {{ .Values.plex.hostNetwork }}
      dnsPolicy: {{ .Values.plex.dnsPolicy }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: mediaserver
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "mediaserver"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: plex
          image: {{ .Values.plex.image }}
          ports:
            - containerPort: 32400
          env:
            - name: TZ
              value: "Europe/London"
            - name: PLEX_CLAIM
              value: ""
            - name: ALLOWED_NETWORKS
              value: "192.168.1.0/24,10.42.0.0/16,10.43.0.0/16"
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.plex.resources | nindent 12 }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
