transmission:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

jellyfin:
  resources:
    limits:
      cpu: "3000m"
      memory: "3000Mi"
    requests:
      cpu: "3000m"
      memory: "3000Mi"

radarr:
  resources:
    requests:
      cpu: "100"
      memory: "256Mi"
    limits:
      cpu: "100"
      memory: "512Mi"
