transmission:
  resources: {}
    # requests:
    #   cpu: "100m"
    #   memory: "256Mi"
    # limits:
    #   cpu: "200m"
    #   memory: "512Mi"

jellyfin:
  resources: {}
    # requests:
    #   cpu: "2000m"
    #   memory: "2000Mi"
    # limits:
    #   cpu: "3500m"
    #   memory: "3000Mi"
plex:
  resources: {}
