transmission:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

jellyfin:
  resources:
    limits:
      cpu: "1500m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"

radarr:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
