ingress-nginx:
  controller:
    ingressClass: nginx
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    extraArgs:
      default-ssl-certificate: nginx-ingress/visar-cloud-tls
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.240
      annotations:
        metallb.io/address-pool: homelab-pool
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: In
                  values:
                    - "true"

