argo-cd:
  configs:
    params:
      server.insecure: "true"
    cm:
      url: https://argocd.visar.cloud
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.visar.cloud/realms/homelab
        clientID: argocd
        clientSecret: $oidc-secret:clientSecret
        usernameClaim: email
        requestedScopes:
          - openid
          - email
          - profile
    rbac:
      create: true
      policy.default: role:readonly
      scopes: "[email]"
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, projects, *, *, allow
        p, role:admin, exec, create, */*, allow
        p, role:admin, logs, get, */*, allow
        p, role:admin, settings, *, *, allow
        g, admin, role:admin
        g, iamvigneshwars@gmail.com, role:admin

  redis-ha:
    enabled: false
  redis:
    nodeSelector:
      kubernetes.io/hostname: rpi1

  controller:
    nodeSelector:
      kubernetes.io/hostname: rpi1
    replicas: 1

  server:
    nodeSelector:
      kubernetes.io/hostname: rpi1
    replicas: 1
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hostname: argocd.visar.cloud
      path: /
      pathType: Prefix
      ingressClassName: nginx

  repoServer:
    nodeSelector:
      kubernetes.io/hostname: rpi1
    replicas: 1

  applicationSet:
    nodeSelector:
      kubernetes.io/hostname: rpi1

  notifications:
    enabled: false
  dex:
    enabled: false
  crds:
    install: true
