---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBxSG6Yjx+80KYgK88jpn2p+Ru1mEAa/Rpt99Q9grcvUqV2qz3MWIG9BVsFeyktnTobXuqI96CuInWPXAoCbaG0J86F+liIj5QgBvCJYYPwhy4P7XR/XhUvpVIUGdtxW4c24INDvCeEaX8pQUnKjX/n5KE6vWluoj0xJPvbdVvtxxRAajTznUn7f2tBXcALusBJ2bgS9Qe2OkbPWOcB087KoSLyZLMsaHSCjynThAO8k4y4Rwt9Lg+YoDrEJ4bNrf8jdmLTvMxzSHaGgnYBry4NdXlD4RGKZZKuHSXybx459x+sLsKuf2P19t0ra796nnhDfzt5wa7n4r3vLz8a4ptds5DdatYnUXI+/HsCCFHUSDR0rgWTpuQTrWQJMyLFPPUsBXncHngJFioxnq1//S1QAQNgtKDtF1AoqXaOfqn9h7hsuB5wTctnfSqsf3upTvd7h0uI+6cMz9X5Vqy9/RB0vcfyULDdqm44ejJAJ5uIYGeJDBXto8ogpv+8F+krGKeVM7UozP5JYBEaV7jAkO9LEVGdCgV+l3jpaYL6cyPCoaeukAz0qxLGiEairE6CDuA5whtOU2tUh6G+wlhvUTcvcrOgYGEoSw3yzsJcD7NFvTOoUES86h45mDdh1hN4vdbUicQYtfcqmjfals9V8pQc4fRaFzcBoTsBSw3vk/Qpm4DC5wnlYKtFXqMBhlunSfkD6tnKD/ZiijNZk8nIbh6y4Cc2TON+h2DV9ItWHkRqCA==
  template:
    metadata:
      name: oidc-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
