---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-cred
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCMHteHW/HcOXnPeBzOYf58bBSUXGskskwKkpbamxuFEPWTPM4SyjBikf2RE8OK6ZcPMnkYEUSuI0g3w7NnhM84x6OhT3u7hwlKbllbbTnXzgye7ne/7Q1VZO0WUhDrQCLfN4iw2emQY4neGt9epqJP3/QynywB4QBkTB9twN1MlCwOUJPq3rS+38mM0fCcXXmZJ5DrT8EQ7oAAZddG3r3jIuCKM/6jdRCpaiXxRafAg1Itg2FG2qoBcFjA7xA97ynw2Lkvvj3e0W+J8kgZAMTKIFfQpAa4k9Tv4BXRyGJdJqzu3x/5Cg7Iv6fUAVV100iAh9V22s/SBfqjHRQ5MjPKpU2v3PLAkz/9rDuk3SV03Way/U8Ft3ajqp74uRS0R4P+g7ZEr9ee83gIbWUHHYhzxSXmMEG1ICxO9j6fFV0Xa56dTjwZ56qESlUWFXQqNRG6SfFgeS4XcwcpFqDV0dWfX28d/coZOENnpwTzlVEbXZelcAw9lHptOseUpeUbt/p2NP4D8V2u27qo/HzFbWkYfZGRO1Ovk9rPlGyXBBLCLIL+T+q7kKM6xnyiZ7xfjIdECzhWl/46COfTxqK0Rpi4inRu9DIzFvLWORik5d7y6hvrTNqBuTTFlsmITz9YH2GiqUcG4GMC855mvyKWwbEKFlVrZJf4rliwC0j4YIlBBAn402b3IZJmYU+PB6huCbfg3juzhw==
    db-password: AgCH+QI2MX94G0MRJ4862YuJnwscyVqHMWFBoZG1f+umXKc/hfWF5D4Mc23pAoXPUiozuZmJO4zR4SYYewlYcCXpWqR7RYCi5HG/ZnBdDhRymSRTKOzvdRcEfN5P2DzacSyIT174uR3cfNYvWuL3OrTQGmlA/sQ6lgP6xgfWvGo0OC+ZYjDaWh1trXNmbnV7TNVpUttH65aOGfeGnhtOKN86btehrPQs+lNqvp8MhxANpWREIFK3y4KHkKwUt2ahhf4KDFh1xOMEoaA4Pzu9uj/kl/brnFYEqwTLzN6CU7srPz8R3f6TMhEO6ERYI9LXriF40Y7qEyfxBNJMnOs7ZKK5h3LO85NCFAuMyVzvYG4r4ihzUXlDbaiQ9Pus4RElu4IDe+gbYU2JTKKkRplJU4Z0WxcOnt3hAD+lM9pnKlKuS1mKb/X2wMyv/TFPCEyQ+fk69ut505/tPB/pS0PW7mHeh2pL7LHK16YfTxNxum2R5rpfUByZGqUCHnI6eaJlGd4y2HfNxTRkieY4N7XWyT0/3AQYhyHLkbkqgyEGR2aFKmVUUoa99wkL73XsGvpoeNxJl0vug1lnIJXtNKR8Vqwb+GUeQi0VknaEETfwB6ZidrcBoUIhDVWOM9ydSdV9dyWLJqvPF80osw08w8cveZooJdxyIJ1DtJ4/JUI1btyWfhAgwgFyPhjae28Wav7PwUnb3HF18zHxMQ==
  template:
    metadata:
      name: keycloak-cred
      namespace: keycloak
