ingress-nginx:
  controller:
    ingressClass: nginx
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.240
      annotations:
        metallb.io/address-pool: homelab-pool
