apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: radarr-downloads
  resources:
    requests:
      storage: 10Gi
