apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: radarr-movies
  resources:
    requests:
      storage: 10Gi
