kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.lan
      path: /
      pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
      storageClassName: nfs-grafana
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    adminPassword: admin
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - rpi1

  prometheus:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.lan
      path: /
      pathType: Prefix
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-prometheus
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 1Gi
  prometheus-node-exporter:
    enabled: true
    prometheus:
      monitor:
        attachMetadata:
          node: true
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: node
        metricRelabelings: []
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
      retention: 3d
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rpi1

  kube-state-metrics:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 200m
        memory: 500Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - rpi1

  prometheusOperator:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - rpi1
