kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.lan
      path: /
      pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
      storageClassName: nfs-grafana
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    adminPassword: admin

  prometheus:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.lan
      path: /
      pathType: Prefix
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-prometheus
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 1Gi
      retention: 7d

  prometheus-node-exporter:
    enabled: true
    prometheus:
      monitor:
        attachMetadata:
          node: true
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: node
        metricRelabelings: []
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi

  kube-state-metrics:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 200m
        memory: 500Mi

  prometheusOperator:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi

  coreDns:
    enabled: false

  defaultRules:
    rules:
      kubernetes: true
  prometheusOperator:
    admissionWebhooks:
      enabled: false
