transmission:
  resources: {}
  persistence:
    config:
      existingClaim: transmission-config
    downloads:
      type: pvc
      existingClaim: transmission-downloads
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: transmission.visar.cloud
        paths:
          - path: /
            pathType: Prefix
    tls: []

jellyfin:
  enabled: false
  resources: {}
    # requests:
    #   cpu: "2000m"
    #   memory: "2000Mi"
    # limits:
    #   cpu: "3500m"
    #   memory: "3000Mi"
plex:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  resources: {}
