pgadmin4:
  env:
    email: "admin@ad.ad"
    password: "admin"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: pgadmin.lan
        paths:
          - path: /
            pathType: Prefix
  nodeSelector:
    kubernetes.io/hostname: rpi2
  persistence:
    enabled: true
    existingClaim: "pgadmin"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      memory: 256Mi
  volumePermissions:
    enabled: true
