Filebrowser:
  persistence:
    data:
      existingClaim: filebrowser-data
    database:
      existingClaim: filebrowser-database

  ingress:
    main:
      enabled: true
      className: nginx
      hosts:
        - host: nas.visar.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
