apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeName: {{ .Values.plex.nodeName }}
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32400
              name: web
          env:
            - name: TZ
              value: {{ .Values.plex.timezone }}
          volumeMounts:
            - name: media
              mountPath: /data
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
          resources:
            {{- toYaml .Values.plex.resources | nindent 12 }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: plex
        - name: transcode
          emptyDir: {}
