apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-data
  nfs:
    server: 192.168.1.252
    path: "/srv/nfs/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-data
  nfs:
    server: 192.168.1.252
    path: "/srv/nfs/data/k8s/filebrowser"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-data
  volumeName: filebrowser-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-data
  volumeName: filebrowser-database
  resources:
    requests:
      storage: 1Gi
