apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    CLIENT_SECRET: AgB2KUwbRWUcyMUdTsHeIPjBPOhE69oyiYle2B8erDJpRpyuEZyiCZhHWHkK5IE5DtNlqt6/H3nc7VsaSPRZpvW+Kvevm7Q8Obt93Qn7cwItMbfYa0A3vkgg3KTlIsPAL7RH3Y/ST7AMOZl01tds1MbOjQRkYokhB20InbTyjnjhXzFcltj5yJF1c2RxPgt12XceeM5bsOzr+UGpfXzjVEFMiVtbS/AsTdl6zJLqZDLUnFNPy7BS5t+906vzOuU+X4boo+yCpu2YY9Fu1WRuyWe8fm9ATYKmvqfiaQnvo7wpSNcv9TUGuZfh4TmqdayGLWp/FXtAGFJ/z8XabwTYbxNOYUfFUqHGUCDvaAKHjDQTw9LTKyZzIIMrOIxDjy+GkhWOJb02/S45bA2X+0L0fcG9S5E15uOxsHfdAqJyq/+aOaMh9LzzDU2LOgAlUbZOHbNPnQeNYDuOIsaeNeEPu7Mj2ferbG/YYRVyl22t4h/V5gDHAutYlVwJr7R+GjkiWupwohY/KYDy30tPa0+FZFpmKqdP/YSTvykwoHGnljLXT308zVwI9whbRVdmfvNXGHOJPMKvqS+cJLJ4xOUhBq/pfICfQj8G6v4g6i2nOD0ZcviBTa3p3gIYvWDVO7+wZZEUZAbZs1Rb88TNFBqwxxtkYCHLk3TJZPZ6RsC0EUY2aSxoGh05l4KGbbcowhzvUtQ+jIsIiqkkVodgukCkFfBDkn7QIuEY4lWGbp+3nkLcHg==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
