apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-grafana
  nfs:
    server: 192.168.1.2
    path: "/mnt/nvmestore/grafana"
