apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus
  nfs:
    server: 192.168.1.3
    path: "/srv/data/k8s/prometheus"
