apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-pgadmin
  local:
    path: /srv/nvme/k8s/pgadmin
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - rpi2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-pgadmin
  volumeName: pgadmin
  resources:
    requests:
      storage: 10Gi

