---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBAzGky7KVgFGIqyL+/1ik4UENoJP2yOy3GcLKwcSwnXQ4A6eIq1WMZW0QYuLVzM3xt3NnXzxPdsgXcxhTXNFrvegK85fqbd5Aj3qzOL2f9n0MpwOzf58xUVSb3oZSSyILZ/170xnSS1OfyshJRTc1T/M/R2j13+DSDPrSbUr0QdJXqY540Otfe0QPa8Vt5A9spWNdJVNt1U7qAQdmAUxfjGqJuBFQzijj1LJ08qZaMcgdQIlhsZHqnIZ+DZ4J93/mHZ1VmVK6xkZH6a9GD3gEOkgrFsS9/s9lLIa22ieCjrlR7zteW+xRgrC4LSCxzdzro02PTUzJMNidlA5v7dCD77iKexm2H3/bo/U6352a54hfchXZlfzCVWDTHp+60l6Xig7NPSGBk5l7umDEtDslIgeq2dlM3GMWEPesWwHEPyI+PqxjtQAjk1/H3bpwhSSaN7Zp6pY5h4FslATzUjdNUJ6iamvyx8vDvQN/7aH+QBq5tI6tY6GKBLIFr9mLNic7WNVsIzz5+9Ag6rb281DAVAgfHq298DxDeVr3X6IFOU9If4sARjcKdxPFmsKlAdQjoodqRZCMx6rDlw2nnKVhJwgHYdQ3n5JKd/E6tRnhc3KTWiCuUCQAJ6S9pNKHeAiAtgRn4jxBlbLIFSNKZeM8KnDFflcDugvF/OcjPYD065jkvZffMKgBYsrodm6rY3/sDMCym+A==
  template:
    metadata:
      name: postgres-auth
      namespace: postgres
