apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-postgres
  local:
    path: /srv/data/k8s/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - rpi2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-postgres
  volumeName: postgres
  resources:
    requests:
      storage: 10Gi
