apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: jellyfin
  resources:
    requests:
      storage: 10Gi
