apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: mediaserver
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "mediaserver"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: jellyfin 
          image: jellyfin/jellyfin:10.11.5
          ports:
            - containerPort: 8096 
          volumeMounts:
            - name: media
              mountPath: /media 
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.jellyfin.resources | nindent 12 }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
