apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: media
  resources:
    requests:
      storage: 10Gi
