apiVersion: v1
kind: PersistentVolume 
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual
  nfs:
    path: /mnt/nvmestore/kube-configs
    server: 192.168.1.47
    readOnly: false 

---

apiVersion: v1
kind: PersistentVolume 
metadata:
  name: media
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage 
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: jellyfin-config
  resources:
    requests:
      storage: 1Gi

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: media
  resources:
    requests:
      storage: 10Gi
