apiVersion: v1
kind: PersistentVolume 
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  hostPath:
    path: /kubeconf/jellyfin-config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: jellyfin-config
  resources:
    requests:
      storage: 1Gi
