apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin 
    spec:
      nodeSelector:
        mediaserver: "true"
      containers:
        - name: jellyfin 
          image: jellyfin/jellyfin:latest 
          ports:
            - containerPort: 8096 
          volumeMounts:
            - name: media
              mountPath: /media 
            - name: config
              mountPath: /config
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
