apiVersion: v1
kind: PersistentVolume 
metadata:
  name: media
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual 
  nfs:
    path: /mnt/nvmestore
    server: 192.168.1.47
    readOnly: false 
