apiVersion: v1
kind: PersistentVolume 
metadata:
  name: radarr-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /kubeconf/radarr

--- 

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: radarr-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: radarr-config
  resources:
    requests:
      storage: 5Gi
