apiVersion: v1
kind: PersistentVolume 
metadata:
  name: radarr-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /mnt/nvmestore/kube-configs
    server: 192.168.1.47
    readOnly: false 

--- 

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: radarr-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: radarr-config
  resources:
    requests:
      storage: 5Gi
