apiVersion: apps/v1
kind: Deployment 
metadata:
  name: radarr 
  labels: 
    app: radarr 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr 
  template:
    metadata:
      labels:
        app: radarr 
    spec:
      nodeSelector:
        mediaserver: "true"
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          ports:
          - containerPort: 7878
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          volumeMounts:
          - name: downloads
            mountPath: /downloads
          - name: media
            mountPath: /media
          - name: config
            mountPath: /config
      volumes: 
      - name: downloads
        persistentVolumeClaim:
          claimName: transmission-downloads
      - name: media 
        persistentVolumeClaim:
          claimName: media
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
