apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual 
  nfs:
    path: /mnt/data/Downloads/Transmission
    server: 192.168.1.47
    readOnly: false 

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: transmission-downloads
  resources:
    requests:
      storage: 10Gi
