apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage 
  hostPath:
    path: /mnt/data/Downloads/Transmission

---

apiVersion: v1
kind: PersistentVolume 
metadata:
  name: transmission-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual
  nfs:
    path: /mnt/nvmestore/kube-configs
    server: 192.168.1.47
    readOnly: false 

--- 

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: transmission-downloads
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: transmission-config
  resources:
    requests:
      storage: 1Gi

