apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  local:
    path: /srv/data/Downloads/Transmission
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - rpi2

---

apiVersion: v1
kind: PersistentVolume 
metadata:
  name: transmission-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  local:
    path: /srv/data/k8s/transmission
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - rpi2

--- 

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: transmission-downloads
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: transmission-config
  resources:
    requests:
      storage: 1Gi

