metallb:
  crds:
    enabled: true
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: In
                  values:
                    - "true"

metallbNamespace: metallb-system

addressPool:
  name: homelab-pool
  addresses:
    - 192.168.1.240-192.168.1.250
