apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: manual 
  nfs:
    path: /export/Data/Downloads/Transmission
    server: 192.168.1.44
    readOnly: false 
