apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: transmission
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: manual 
  volumeName: transmission 
  resources:
    requests:
      storage: 10Gi
