headlamp:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: headlamp.visar.cloud
        paths:
          - path: /
            type: Prefix
    tls:
      - hosts:
          - headlamp.visar.cloud
