apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-sealedsecret
  namespace: nginx-ingress
spec:
  encryptedData:
    api-token: AgCcgWhZa2i90q5CZUSIZTgog1EeXWCbhT9P7xc7XgMed0XzrM0DH1x9rPh8CxRftX2WA2UUOqUj5XbNlo2ZoMJrKoOD7JSU3iYn2GdFObBVa4STt203GQx3JU9T/75cnAhwrnkZ0IqkyLOeZ46+wu6+NyaYQtMEqPu0ahz58ENn8o7t75OuJ4r8DadV/1VYzGMPjWEMw8FrQa9F+u6/AMBpv00dfoG07Hsb2owFC4PIFsoXipBbI7oIjfEwRLB1AoMDK/CCWulR0xxWQw8F8m8kYmicnsTz2OSynxN1H8bg90aR2RVbhLGEGXWOBUuzp/vTCbCG6h6AMTOvjjrT5T9CAwoM999oc7VAR7oA5h4R/QWmTdL91pWLcPpDUdGmOIxkW3BlBe+uUGq6j2yBzBzhMB85E16kVAgG9FaZ3fsE+o72BbIBl62JmcePB3SE+cNtYn/J6NTbutgfeNeubelitKO84L1k6OXQ+YhhGqiyhjwUm/G7L2wFTwspcki2Pa9tHM9RjQ/3SnuLlVJXCvefKVugFz6oJFBFHqqvKMQAueUA/mEH2Gsy5kWMPFOjK5ctZhG1UJ9nr7Ms7saQuLLqbiXVo8Ys0gCSnggvx9XCGSIOGvYdRXJcSDpWi8TOtaXt6tYoQBlrBAP8y8lIW6ia0YmnLFpVzvLu8Ol+G98RJFEtmCcklpHGQjbsQHnnA+NlNf097q3AVULKuHDd4sX+U/HwNyrggz8FVOa7ElQPyRL6YXFCSSLl
  template:
    metadata:
      name: cloudflare-sealedsecret
      namespace: nginx-ingress
