apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: services-key
  namespace: homepage
spec:
  encryptedData:
    adguardPassword: AgAetTwA8z7Xi9JkU7aPOxnZJeY374BIPX7p9C2m2Tcw+h0aflKFdyJxTDUQ75KUN+5rYzEDRwaif1ln5/AdIElrWA+/IUWjGB4nLhOwRTiiMKdEbnuhIL5nDLifeHHFf2m7EYFBTGrkcYTJ0XjyV2bpGN6b5PjSafYPtR5Jp9YvJiy//4c1vzlqDElCrq2dD0P8yqcyKh13YO1fqA3XaEt3ZnGEPFg5EIxmTisgWNvSZCPf1nVFbpoa/bT5YGDDSEozMyzicL7Azhi83FrUZ75+nNr+cPazhnAaE//mBnkhrRiJJt4acca7nIO/bCjycPH9As67V7XND15tujFDpvWi1uoIWYVdnpn1Th8/IGTKJlnkQxLZEtpdpFN6KePI8QMbqnCuAqvW+YXOGq4XabpSJ+Axsy+1lami1DxXw77LZOmdNUUG1GCAkO3MPF2+VmT31bQb01Bn4WP9WiE4pnsvVF0mcEVCF6hPnaVOJzxdL6Vpnc45o1usYWnzEcRkmSRz0WufRz591gyIwEu4BW7b3KLTUHhJeppkd83q5nCTKAf8Pel8gSaNBEPoZ3TKKkZYs4RxqrM2R1G/w+eVkWM3KjLXZdH8LMm1Cus/ZS/W2WLTcIXC5+D9Xk+Vj7LoapQjDzOC2GMoswXB7WkaULVmDurUiPH3hvMJPFrIMfdGd9w0qEqlZ2vUmmGYbB66qQYDiVtglGnJlFnV9ss=
  template:
    metadata:
      name: services-key
      namespace: homepage
