apiVersion: v2
name: postgresql
description: Standalone PostgreSQL for Keycloak
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 18.1.10
    repository: https://charts.bitnami.com/bitnami
