keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: "26.5.4"

  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      - hosts:
          - keycloak.visar.cloud
    rules:
    - host: keycloak.visar.cloud
      paths:
      - path: /
        pathType: Prefix

  postgresql:
    enabled: false

  nodeSelector:
    kubernetes.io/hostname: rpi1

  extraEnv: |
    - name: KC_HOSTNAME
      value: "keycloak.visar.cloud"
    - name: KC_PROXY_HEADERS
      value: "xforwarded"
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KEYCLOAK_ADMIN
      value: "admin"
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-cred
          key: admin-password
    - name: KC_DB
      value: "postgres"
    - name: KC_DB_URL
      value: "jdbc:postgresql://192.168.1.241:5432/keycloak"
    - name: KC_DB_USERNAME
      value: "keycloak"
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-cred
          key: db-password
    - name: KC_HTTP_MANAGEMENT_HEALTH_ENABLED
      value: "false"
    - name: KC_HEALTH_ENABLED
      value: "true"

  livenessProbe: |
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5

  readinessProbe: |
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 1

  startupProbe: |
    httpGet:
      path: /health/started
      port: http
    initialDelaySeconds: 30
    failureThreshold: 60
    periodSeconds: 5
