apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: visar-cloud
  namespace: nginx-ingress
spec:
  secretName: visar-cloud-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "visar.cloud"
    - "*.visar.cloud"
